#!/bin/bash
# VistA RPC Broker TCP listener (port 9430)
# Replaces xinetd.d/vista-rpcbroker. Launched by bin/start.sh.
exec socat \
    TCP-LISTEN:9430,fork,reuseaddr \
    SYSTEM:'REMOTE_HOST="$SOCAT_PEERADDR" exec /home/foia/bin/rpcbroker.sh',su=foia,stderr
